# Node docker image on which this would be run
image: node:latest

cache:
  paths:
    - node_modules/

# Pipeline:
stages:
  - install
  - build
  - test
  - deploy
  - production

# Jobs:

install_dependencies:
  stage: install
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/


tests:
  image: cypress/base:10
  stage: test
  before_script:
    - npm install -g httpserver
    - npm install cypress
    - npm run start:server
  script:
    - npx cypress run --record --key=$CYPRESS_RECORD_KEY

deploy_staging:
  only:
    - develop
    - master
  stage: deploy
  before_script:
    - npm install
    - npm run build
    - npm install -g surge
  script:
    - mv CNAME-S CNAME
    - cp CNAME dist
    - surge dist
    - echo "Deployed to staging server"

continuous_delivery:
  only:
    - develop
  stage: production
  before_script:
    - npm install
    - npm run build
    - npm install -g surge
  script:
    - mv CNAME-P CNAME
    - cp CNAME dist
    - surge dist
    - echo "Deployed to production server"

continuous_deployment:
  only:
    - master
  stage: production
  before_script:
    - npm install
    - npm run build
    - npm install -g surge
  script:
    - mv CNAME-P CNAME
    - cp CNAME dist
    - surge dist
    - echo "Deployed to production server"

